### ISSUE TITLE
No `story validator status` in v0.10.0-x86

### ISSUE THREAD

**Issue by carawaylj** [piplabs/story#118]
## Steps to reproduce

1. download https://story-geth-binaries.s3.us-west-1.amazonaws.com/story-public/story-linux-amd64-0.10.0-9603826.tar.gz
2. unzip  and use the new story to run cli `story validator status`

## Experienced behavior

ommands for validator operations
```
Usage:
  story validator [command]

Available Commands:
  add-operator           Add a new operator to your delegator
  create                 Create a new validator
  export                 Export the EVM private key from the Tendermint key file
  remove-operator        Removes an existing operator from your delegator
  set-withdrawal-address Updates the withdrawal address that receives stake and reward withdrawals
  stake                  Stake tokens as the delegator
  stake-on-behalf        Stake tokens on behalf of a delegator
  unstake                Unstake tokens as the delegator
  unstake-on-behalf      Unstake tokens on behalf of a delegator

Flags:
  -h, --help   help for validator
```

## Expected behavior

It shoud show the latest block height  (in the release note )

**Comment by edisonz0718** [comment]
Please use this release before using cosmovisor for upgrades: https://github.com/piplabs/story/releases/tag/v0.9.13
It adds the status command
