### ISSUE TITLE
Failed to sync after upgrade to 0.10 with errors

### ISSUE THREAD

**Issue by carawaylj** [piplabs/story#119]
## Steps to reproduce

1. Download and update 0.10 binary and restart
2. check logs

## Experienced behavior

Logs shows error 
`24-09-13 03:01:27.714 ERRO Finalize req failed [BUG]                height=486474 err="unmarshal validator sweep index: proto: wrong wireType = 2 for field NextValIndex" stacktrace="[errors.go:39 params.go:106 withdraw.go:21 abci.go:133 module.go:146 module.go:804 app.go:170 baseapp.go:792 abci.go:819 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:219 replay.go:534 replay.go:433 replay.go:274 setup.go:182 node.go:359 node.go:279 start.go:207 start.go:133 start.go:56 cmd.go:51 command.go:983 command.go:1115 command.go:1039 command.go:1032 cmd.go:34 main.go:10]"
24-09-13 03:01:27.714 ERRO error in proxyAppConn.FinalizeBlock      module=consensus err="unmarshal validator sweep index: proto: wrong wireType = 2 for field NextValIndex" stacktrace="[errors.go:39 params.go:106 withdraw.go:21 abci.go:133 module.go:146 module.go:804 app.go:170 baseapp.go:792 abci.go:819 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:219 replay.go:534 replay.go:433 replay.go:274 setup.go:182 node.go:359 node.go:279 start.go:207 start.go:133 start.go:56 cmd.go:51 command.go:983 command.go:1115 command.go:1039 command.go:1032 cmd.go:34 main.go:10]"
24-09-13 03:01:27.714 ERRO !! Fatal error occurred, app died️ unexpectedly !! err="create comet node: create node: error during handshake: error on replay: unmarshal validator sweep index: proto: wrong wireType = 2 for field NextValIndex" stacktrace="[errors.go:39 start.go:217 start.go:133 start.go:56 cmd.go:51 command.go:983 command.go:1115 command.go:1039 command.go:1032 cmd.go:34 main.go:10 proc.go:271 asm_amd64.s:1695]"`
## Expected behavior

Should sync successful with height increasing in the logs

**Comment by Coha05** [comment]
That not issue then mate, u just hurry upgrade before block `626,575`

**Comment by cnsilvan** [comment]
same here

**Comment by edisonz0718** [comment]
0.10 is a hard fork. It needs to reach the upgraded height first before swapping the binary. DIrect upgrade to 0.10 won't work at this point. More details see: https://medium.com/story-protocol/story-v0-10-0-available-for-coming-upgrade-e2f9cb10443b
