### ISSUE TITLE
Story directly upgrades without waiting for planned block

### ISSUE THREAD

**Issue by mrheed** [piplabs/story#123]
## Description and Context
I am unable to use the **auto-upgrade feature** in **Cosmovisor**. Whenever I execute the `add-upgrade` command, it immediately switches to the new binary, instead of waiting for the specified upgrade height. I am currently running binary version **v0.9.13** and latest version of cosmovisor.

## Steps to Reproduce
1. I ran the following command to add an upgrade:
   ```bash
   DAEMON_NAME=story DAEMON_HOME=~/.story/story cosmovisor add-upgrade v0.10.0 story_upgrades/story-v0.10.0 --force --upgrade-height 626575
   ```

2. The upgrade binary was placed in the appropriate directory:
   ```bash
   ~/.story/story/cosmovisor/upgrades/v0.10.0/bin/story
   ```

## Expected Behavior
I expected Cosmovisor to switch the binary at the specified upgrade height **(626575)**.

## Experienced Behavior
Instead of waiting until the specified upgrade height, Cosmovisor switches to the new binary immediately after I run the `add-upgrade` command.

**Comment by edisonz0718** [comment]
Please use this release before using cosmovisor for upgrades: https://github.com/piplabs/story/releases/tag/v0.9.13
It adds the status command that cosmovisor reads from.

**Comment by mrheed** [comment]
> Please use this release before using cosmovisor for upgrades: https://github.com/piplabs/story/releases/tag/v0.9.13 It adds the status command that cosmovisor reads from.

right, the issue are already solved, my problem was because the the genesis binary is not version 0.9.13
