### ISSUE TITLE
No cometbft_consensus_validator_missed_blocks prometheus metric after v0.10.0 upgrade

### ISSUE THREAD

**Issue by joeAtKysenpool** [piplabs/story#130]
`curl -s 127.0.0.1:<rpcport>/metrics |grep cometbft_consensus_validator_missed_blocks` returns blank, while 4 other cometbft_consensus_validator* metric has values.

```
cometbft_consensus_validator_last_signed_height{chain_id="iliad-0",validator_address="<hex>"}
cometbft_consensus_validator_power{chain_id="iliad-0",validator_address="<hex>"} 
cometbft_consensus_validators{chain_id="iliad-0"} 100
cometbft_consensus_validators_power{chain_id="iliad-0"} 1.18458330745e+11
```

**Comment by edisonz0718** [comment]
Do you observe non-empty value previously and if so, when did you notice the change?

**Comment by joeAtKysenpool** [comment]
it was non-empty value in v0.9.12 for sure.

**Comment by joeAtKysenpool** [comment]
actually it's in v0.9.13 as well.. looks like last value is on `2024-09-17 17:38:00`UTC.. so that's block time for the v0.10 upgrade.

**Comment by joeAtKysenpool** [comment]
so the `cometbft_consensus_validator_missed_blocks` metric came back on `2024-09-19 07:00:00` with `1` missing block.  
So appears that `cometbft_consensus_validator_missed_blocks` key won't show if there is no missing block? 
Should have the key in the metric with value as `0` if there wasn't any missed blocks.

**Comment by edisonz0718** [comment]
Got it. Thanks for letting us know. 

Yes, I agree that 0 is a better representation here. This part is implemented by cometbft. We can create an issue to them to suggest this change.
