### ISSUE TITLE
Unauthorized Staking Bug with stake-on-behalf Command

### ISSUE THREAD

**Issue by Coha05** [piplabs/story#148]
## Description and context
There is a bug in the `stake-on-behalf` command that allows tokens to be staked from a delegator's wallet without requiring the delegator’s private key. My friend, @roscuong, mistakenly used my public key as the `delegator-pubkey` and his own validator's public key as the `validator-pubkey`, causing 1.3k tokens to be staked from my wallet to his validator. This happened even though I did not authorize the transaction with my private key.

Additionally, @roscuong initially received 1.3k tokens from the staking service "stakeme." Despite staking to his own validator, it remained inactive, so I asked him to stake the tokens to my validator, which triggered the issue.
## Steps to reproduce
1. My friend @roscuong received 1.3k tokens from "stakeme."
2. He ran the `stake-on-behalf` command, but mistakenly swapped the `delegator-pubkey` (my public key) and `validator-pubkey` (his validator's public key).
3. The transaction completed, and tokens were staked from my wallet to his validator without my private key being used.
His staked tx: https://testnet.storyscan.xyz/tx/0xbace3d558b9d3cc89abd2cafdd83a6d4f0b4788ac8f3e7cad04f8e65658f5847
His validator: https://testnet.story.explorers.guru/validator/9AD59F9A8A459127CB7BA28C009887DF6F8D1D79
4. My wallet shows on his validator 
![1st](https://github.com/user-attachments/assets/82f26ccc-8c80-473c-a4d3-9cedc7ee9997)

## Experienced behavior
The tokens were successfully staked from my wallet to his validator without my private key authorization.
@roscuong is unable to unstake the tokens.
I (the delegator) still have control over the staked tokens and can manage them (e.g., unstake or stake with my private key).
Tx unstake from MY wallet: (testing for make sure it works with my private key)
1. https://testnet.storyscan.xyz/tx/0xb08188252a6be9c72dc3e119235a9bdfea39872c95d825b35615538946d5beb7
2. https://testnet.storyscan.xyz/tx/0xdd6166e859e724906cda1fee15ebe4c953403781b5098dd0b316afd1ad4b9da6
3. https://testnet.storyscan.xyz/tx/0x201f863085e75b86b772f45b21e804db4ed7b8704d271cb77e654a5122054cbe

Here screenshot show unbonding from my wallet which tokens I don't really have, that tokens from him.
![2nd](https://github.com/user-attachments/assets/94b86157-586d-4d4f-bbd3-8e2d23fbaf71)

And here is his wallet no unbonding status but the tokens really from him.
![3rd](https://github.com/user-attachments/assets/be806d92-1813-42e4-950e-782aa61ff683)

## Expected behavior
The staking transaction should not proceed unless the delegator (me) authorizes the transaction with my private key. Any staking from my wallet should require my explicit authorization.
## Solution recommendation
The staking process should enforce proper verification of private key ownership when using the `stake-on-behalf` command. This would prevent staking from a wallet without the owner’s explicit authorization.

---
**Update:**

In result after 1 hour unstake, 1k3 tokens back to my wallet not his wallet. 

**HE LOST HIS 1k3 TOKENS by above action.**

![image](https://github.com/user-attachments/assets/c712fe27-f998-4385-977b-7a1b544fb482)

Another point of views: https://github.com/piplabs/story-geth/issues/23

**Comment by Coha05** [comment]
**Update:**

In result after 1 hour unstake, 1k3 tokens back to my wallet not his wallet. 

**HE LOST HIS 1k3 TOKENS by above action.**

![image](https://github.com/user-attachments/assets/c712fe27-f998-4385-977b-7a1b544fb482)

**Comment by jdubpark** [comment]
Please refer to [this cross-posted comment](https://github.com/piplabs/story-geth/issues/23#issuecomment-2379086090) on how `stakeOnBehalf` works. 

The summary is that your friend paid 1300 IP to stake on behalf of you, which essentially means that he has paid 1300 IP to you and staked that amount on behalf of you to the designated validator (because he initially paid for it). Now you own 1300 IP and only you can unstake it.

This behavior is widespread in DeFi, e.g. Aave allows paying debt on behalf of a debtor.
