### ISSUE TITLE
Takes too long to process `setting new local account`

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#191]
1. set DatabaseCache = 8192
2. Setting new local account    address=0x9A0c4B4997485F51FF1013F7080464780BA8b67D still takes around 15 mins

**Comment by edisonz0718** [comment]
Is this still an issue? @lucas2brh

**Comment by lucas2brh** [comment]
This issue was not observed during the last hard fork. Marking it as resolved and closing.
