### ISSUE TITLE
Stake to non-existent validator, tokens are not returned after wait 1 min

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#219]
## Description and context
Stake to non-existent validator, token is not returned after 1 min

## Steps to reproduce
1. A wallet stake to non-existent validator
2. Wait 1 min
3. Check the wallet balance

## Experienced behavior
The staked tokens are not returned.

## Expected behavior
The staked token should be returned.

**Comment by limengformal** [comment]
This is expected. Refund is not in scope now.
