### ISSUE TITLE
After stakeOnBehalf or stake with fixed period, voting power isn’t updated

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#220]
## Description and context
After stakeOnBehalf or self-delegate with fixed period, voting power isn’t updated

## Steps to reproduce
1. create validator (voting power is updated)
2. stake with fixed period
3. check voting power

## Experienced behavior
The voting power isn't updated.

## Expected behavior
The voting power should be updated with stake amount.

**Comment by limengformal** [comment]
Got this error message at CL side:
```
24-10-17 21:13:01.485 ERRO Failed to process deposit                err="delegate: period info not found for period type 180" stacktrace="[errors.go:39 deposit.go:125 keeper.go:188 msg_server.go:112 tx.pb.go:290 msg_service_router.go:175 tx.pb.go:292 msg_service_router.go:198 baseapp.go:1015 baseapp.go:953 baseapp.go:762 abci.go:790 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:202 state.go:1772 state.go:1682 state.go:1617 state.go:1655 state.go:2335 state.go:2067 state.go:929 state.go:836 asm_amd64.s:1695]"
```

**Comment by limengformal** [comment]
@jia57b Locked validator will convert fixed period stake to flexible stake.
