### ISSUE TITLE
For fixed peroid staking, unstaking after staking period ends, token is not returned to wallet

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#221]
## Description and context
For fixed peroid staking, unstaking after staking period ends, token is not returned to wallet

**Comment by jacqueline-57b** [comment]
Tried to unstake before staking period end, and check the wallet balance until staking + unbonding period end, token is also not returned to wallet.

**Comment by Reecetaylor96** [comment]
> Tried to unstake before staking period end, and check the wallet balance until staking + unbonding period end, token is also not returned to wallet.



It sounds like you're facing an issue with unstaking your tokens after the staking period ends.

**Comment by limengformal** [comment]
@ezreal1997 fixed period stake works but fixed period unstake doesn't work. Error message:
```
24-10-17 20:36:09.314 ERRO Failed to process withdraw               err="undelegate: period delegation does not exist" stacktrace="[errors.go:39 withdraw.go:313 keeper.go:210 msg_server.go:112 tx.pb.go:290 msg_service_router.go:175 tx.pb.go:292 msg_service_router.go:198 baseapp.go:1015 baseapp.go:953 baseapp.go:762 abci.go:790 abci.go:884 cmt_abci.go:44 abci.go:95 local_client.go:185 app_conn.go:104 execution.go:224 execution.go:202 state.go:1772 state.go:1682 state.go:1617 state.go:1655 state.go:2335 state.go:2067 state.go:929 state.go:836 asm_amd64.s:1695]"
```

**Comment by limengformal** [comment]
@Ramarti Staking contract should not need to covert period number to seconds.

**Comment by limengformal** [comment]
Issue was fixed by PR: https://github.com/piplabs/story/pull/224

**Comment by lucas2brh** [comment]
@[Staking-10-02](https://www.notion.so/storyprotocol/Staking-10-02-ca5d7637d8b9414999d1ca13d77eec10?pvs=24) passed after fix.
