### ISSUE TITLE
Cannot unstake all IPs if the remaining less than 1024 IPs

### ISSUE THREAD

**Issue by jacqueline-57b** [piplabs/story#233]
## Description and context

Unstake some and remaining less than 1024 IPs, cannot unstake all IPs

## Steps to reproduce

1. Create a ghost validator with staking 2048 IPs
2. Unstake 1025 IPs

## Experienced behavior

1, Unstake 1025 IPs transaction success
2, Check the voting power after unstake, the voting power is 1023 * 10 ** 3

## Expected behavior

If the remaining IPs are less than 1024, all IPs should be unstaken.

**Comment by jia57b** [comment]
test link: https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L1833

**Comment by limengformal** [comment]
Test cases:
[Staking-08-02](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L1849)
[Staking-53](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/stakeUnstake.test.ts#L1827)

**Comment by jdubpark** [comment]
The root cause is [this change](https://github.com/piplabs/cosmos-sdk/blob/1ba12996b6434d03fedc7296f7a4f476e646fcf8/x/staking/keeper/msg_server.go#L457-L467) we had in the staking module's Undelegate (in msg_server.go):
```go
func (k msgServer) Undelegate(ctx context.Context, msg *types.MsgUndelegate) (*types.MsgUndelegateResponse, error) {
	...
	minUndelegation, err := k.MinDelegation(ctx)
	if err != nil {
		return nil, err
	}
	// undelegation amount must be greater than or equal to minimum undelegation
	if msg.Amount.Amount.LT(minUndelegation) {
		return nil, errorsmod.Wrap(
			sdkerrors.ErrInvalidRequest,
			"undelegation amount is less than the minimum undelegation amount",
		)
	}
	...
}
```

**Comment by lucas2brh** [comment]
Confirmed that the test passed on the devnet with 2 test case : [Staking-08-02](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L1849)
[Staking-53](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/stakeUnstake.test.ts#L1827).
