### ISSUE TITLE
Redelegate transaction reverted with error code: UNSUPPORTED_OPERATION

### ISSUE THREAD

**Issue by tyitang** [piplabs/story#235]
## Description and context

Redelegate transaction reverted with error code: UNSUPPORTED_OPERATION

## Steps to reproduce

Call redelegate, the transaction reverted with this error:
`
- Error: no matching fragment (operation="fragment", info={ "args": [ [ "0x04dbf0b8aa32fae64904761b7da12c98a41acd2c6906c45d7f84453899f4a57439bf7787d4155d6f566b396b0ff2e4e1d25e9af89c483b11045a87bc223c07bdcd", "0x04d25dc11cfc4fb28bfb41d6468ed2ae3d35ff456f7a1b7e49929b9e50eb2b58cc7ffe5da5aa41b2e0b1fdd826601a1e19a498650ce6ccb4be3fbf8c65fb3b63ac", "0x04d99d454184facbf6a03ea37eb36f6a50c69842ea3ad42038a8d5537bd15b25941a7b1cc4bf9785364b7610f33584528d74adbb1f132f0942cb176299234a11e5", 0, 1024000000000000000000 ] ], "key": "redelegate" }, code=UNSUPPORTED_OPERATION, version=6.13.2)`

**Comment by Ramarti** [comment]
That's an ethers.js error, the call is not finding a method signature for `redelegate` with those arguments.
Are the ABI and bindings up to date?

**Comment by tyitang** [comment]
test script issue, close the ticket
