### ISSUE TITLE
Call unjail return transaction confirmed but validator status is still jailed

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#250]
## Description and context
Call unjail return transaction confirmed but cannot find the validator in active set

## Steps to reproduce
There is a validator in jail (offline long time or self-delegation is less than 1024)
Call unjail with validator key and 1 fee, the transaction is confirmed, but validator status is still jailed, stake on the validator can not make it become active validator set.

**Comment by lucas2brh** [comment]
Confirmed not an issue, closing.
