### ISSUE TITLE
Validator set change at singularity_height + 2 instead of at singularity_height + 1

### ISSUE THREAD

**Issue by tyitang** [piplabs/story#254]
## Description and context

Create validator and stake during the singularity period, the validator set changed at singularity_height + 2 instead of at singularity_height + 1

## Steps to reproduce

1. Create validator and stake during the singularity period
2. After the singularity period ends, check the validator set at height 601 and 602
`curl --location 'https://devnet.storyrpc.io/validators?height=601'`

**Comment by 0xHansLee** [comment]
This is the way how cometbft consensus works.
As you can see the below picture, the validator set is updated at `H+2`, thus you can get the updated list of validators.
And newly updated validator set actually join the consensus from `H+3`.

ref) cometbft docs: https://docs.cometbft.com/v0.38/spec/abci/abci++_methods

<img width="694" alt="스크린샷 2024-10-19 오후 10 00 07" src="https://github.com/user-attachments/assets/0e365f9d-3564-41c7-9452-b0ee2d022d4c">
