### ISSUE TITLE
create validator on an existing validator, both voting_power and wallet balance are not decreased

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#262]
## Description and context
create validator on an existing validator, voting_power isn't changed but wallet balance is decreased

## Steps to reproduce
1. createValidator with 5000 IP unlocked
2. stake 1024 with fixed period
3. unstake 1024 with delegation id of step 2
4. unstake 5000 with delegation id 0
5. createValidator with 5000 IP unlocked again
6. wait staking period
7. check voting_power  -> 1024000
8. wait unbonding time
9. check wallet balance -> balance is decreasd by 5000

## Experienced behavior
in step 7: voting_power is 1024000, that means step5 createValidator doesn't work
in step 9: wallet balance is decreased by 5000, not sure if it's expected result.

This is test code:
https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L2716

**Comment by limengformal** [comment]
@jia57b This is expected behavior

**Comment by jia57b** [comment]
@limengformal according to the [test result](https://storyprotocol.github.io/l1-tests/20241023/odyssey-devnet/l1-test-report.html#stakeTest) today, the actual result is wallet balance isn't decreased by 5000, can you confirm which one is expected?
Test is : [Staking-56](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L2728)

**Comment by limengformal** [comment]
Probably step 4's unstake wasn't in before step5 due to unbonding time, so step 9 was checking wallet_at_step4 + 5000 (unbonded step 4 withdrawal) - 5000 (createValidator stake)

**Comment by jia57b** [comment]
@limengformal step 4's unstake can get back delegation id 0 balance (no staking period), so the last step [currentBalance](https://github.com/storyprotocol/l1-tests/blob/main/tests/stake/createValidator.test.ts#L2803) should minus 5000

**Comment by limengformal** [comment]
@jia57b Does it wait for unbonding period?

**Comment by jia57b** [comment]
@limengformal The test waits 20 second after the unstake tx confirmed, so should be get tokens back after step4's unstake

**Comment by jia57b** [comment]
@limengformal this is the simple test Staking-56-02: https://github.com/storyprotocol/l1-tests/blob/debug-stake-56/tests/stake/createValidator.test.ts#L2831

1. Create validator with 5000 IP unlocked
2. Check voting power
3. Check wallet balance
4. Create validator with 1024 IP again unlocked
5. Check voting power
6. Check wallet balance

Actual result:
step5: voting power is the same as step 2.
step6: wallet balance is close to step 3.

Here is logs:
```
    Staking-56-02: create validator on existent validator
Current balance of 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1 - latest: 6043998756342980137483
Wallet balance formatted: 6043.998756342980137483
Current balance of 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1 - latest: 6043998756342980137483
validator pub key: A39OHZi7KoaLM9qI2I1+xtLHMNRknnQJxsx0DbhofQJv
Can't find the PUBKEY A39OHZi7KoaLM9qI2I1+xtLHMNRknnQJxsx0DbhofQJv in validators
--- Start to createValidator ---
Sender address: 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1
Creating validator...
Transaction start time: 2024-10-25T03:31:00.606Z
hash 0x55c70df90fc4f1d0d2530630ff618a088ec44893584ed52a5f2a4bdc37dd8016
Creating validator done
Transaction confirm time: 2024-10-25T03:31:07.592Z
Time taken to createValidator: 6986 ms
      ✔ Step01: Create validator with 5000 IP unlocked (21992ms)
Current voting power: 5000000
      ✔ Step02: check voting power (401ms)
Current balance of 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1 - latest: 1043997866838972965857
      ✔ Step03: check wallet balance (301ms)
--- Start to createValidator ---
Sender address: 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1
Creating validator...
Transaction start time: 2024-10-25T03:31:23.302Z
hash 0xec73e364f167b607cd8e494e3cb7177df1e4c1d99fd96b8f7e353c7dd1ae549f
Creating validator done
Transaction confirm time: 2024-10-25T03:31:30.307Z
Time taken to createValidator: 7005 ms
      ✔ Step04: Create validator with 1024 IP again unlocked (22015ms)
Current voting power: 5000000
      ✔ Step05: check voting power (850ms)
Balance before:  1043.997866838972965857
Current balance of 0x7A4a27343D5D14f7a2cA9e3dA74bf11Cda24b1D1 - latest: 1044000338214965794231
Balance after:  1044.000338214965794231
      1) Step06: check wallet balance
Current voting power: 5000000
```
