### ISSUE TITLE
H-2 Malicious proposer can DoS the chain by sending an invalid timestamp

### ISSUE THREAD

**Issue by christianvari** [piplabs/story#299]
## Description and context

In the startBuild function, executed as part of the ABCI PrepareProposal, sets the timestamp in PayloadAttributes to match the node’s current time. If the current time is less than the previously recorded time, the function simply increments the timestamp by 1. 

https://github.com/piplabs/story/blob/7c04757f017b5bbee8f0a842b4c6136c7d62d59d/client/x/evmengine/keeper/abci.go#L231-L234

However, within the makeProcessProposalHandler, there is no validation logic to allow other validators to check if the provided timestamp is accurate. This allows a proposer to set an invalid timestamp, which will affect subsequent proposals since the system enforces monotonicity. 

As a result, the ExecutionPayload message handler would error in parseAndVerifyProposedPayload causing the transaction to fail and creating an empty block.

Additionally, timestamp can be resetted if the last valid one is the max int. When the next proposer will apply ts+1, it will go to 0.

## Solution recommendation

A possible solution would be to execute the parseAndVerifyProposedPayload function on nodes when validating the proposed block instead than on deliverTx.

**Comment by edisonz0718** [comment]
As discussed, the timestamp validation logic already exists in processProposal stage
