### ISSUE TITLE
Max unstake/redelegate within unbonding period 

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#304]
## Description and context

Manually tested the Max unstake within the unbonding period in testnet, and the 15th unstake transaction was still successful, which is not as expected.
The same issue occurred with Max redelegate within the unbonding period.

Test case: 

- Staking-[50](https://github.com/storyprotocol/l1-tests/blob/406f343fb609ad637586d23651cd9c713883a80c/tests/long-time-test.test.ts#L399C15-L399C25): Max unstake within unbonding period
- Staking-[106](https://github.com/storyprotocol/l1-tests/blob/406f343fb609ad637586d23651cd9c713883a80c/tests/long-time-test.test.ts#L459): Max redelegation within unbonding period

## Steps to reproduce

1. create a ghost validator with 1024 * 15 IP.
2. perform max unstake (14 times) tokens (1024 IP) using the same wallet.
3. perform the 15th unstake operation, and expect failure, which does not happen.

**Comment by 0xHansLee** [comment]
Can we close this issue @lucas2brh ?

**Comment by lucas2brh** [comment]
@0xHansLee  can you share the script you tested locally?

**Comment by lucas2brh** [comment]
Closing, confirmed that the initial test result was inaccurate due to the testnet still being in singularity, which disallows unstake and redelegate requests.

Additionally, ran a test on the mininet:

logs(incomplete)
<details><summary>Details</summary>
<p>
    Staking-50: Max unstake within unbonding period
Current balance of 0x2A5672Cf3f798b0F36441137cf4ec0a371d8db8D - latest: 0
Wallet balance formatted: 0.0
Transaction start time: 2024-11-07T15:42:53.016Z
current nonce:  4
Estimated gas: 21000n
Gas price: 16000000007n
Transaction confirm time: 2024-11-07T15:43:00.224Z
Time taken to send transaction: 7208 ms
Current balance of 0x9dF398707CD67f140eb19F59286b3D04CF7C383f - latest: 0
Wallet balance formatted: 0.0
Transaction start time: 2024-11-07T15:43:00.439Z
current nonce:  5
Estimated gas: 21000n
Gas price: 16000000007n
Transaction confirm time: 2024-11-07T15:43:07.857Z
Time taken to send transaction: 7418 ms
bech32 validatorAddr:  storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn
bech32 validatorDelegatorAddr:  story1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jw9r0tc
      ✔ step 00: query bech32 address (82ms)
--- Start to createValidator ---
Sender address: 0x2A5672Cf3f798b0F36441137cf4ec0a371d8db8D
Creating validator...
Transaction start time: 2024-11-07T15:43:07.944Z
hash 0x0d6b3ded8b88a472e84bcf11f8a2b4a592cc099b15fd35318ef7209191624656
Creating validator done
Transaction confirm time: 2024-11-07T15:43:14.079Z
Time taken to createValidator: 6135 ms
      ✔ step01: Create validator (21141ms)
Current balance of 0x9dF398707CD67f140eb19F59286b3D04CF7C383f - latest: 15460000000000000000000
Current balance before staking:  15460000000000000000000
      ✔ step02: Get delegator wallet balance (541ms)
--- Start to stake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Staking...
Transaction start time: 2024-11-07T15:43:29.630Z
hash 0x26618807b3a1cea16b8be6efa5a15f6299319e7146408a5f4331cc6241188a92
delegationId 0n
Staking done
Transaction confirm time: 2024-11-07T15:43:35.758Z
Time taken to stake: 6128 ms
      ✔ step03: Stake 15360 IP with validator (21133ms)
Current balance of 0x9dF398707CD67f140eb19F59286b3D04CF7C383f - latest: 99999164735999634572
Current balance after staking:  99999164735999634572
      ✔ step03-01: Get delegator wallet balance after staking (545ms)
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:43:51.310Z
hash 0x20235dc9ab53c3efbb50274a2f9691eda9f9cd521e5fb03c38b411675e57ef9e
Unstake done
Transaction confirm time: 2024-11-07T15:43:57.488Z
Time taken to unstake: 6178 ms
Unstake operation 1 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:44:17.497Z
hash 0x53e29b02e2974313b93ace9f556faa9f5154b1df7eeb80d2b5f927732603dd07
Unstake done
Transaction confirm time: 2024-11-07T15:44:24.067Z
Time taken to unstake: 6570 ms
Unstake operation 2 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:44:44.074Z
hash 0xcbfdaa86e64c991eb25dcefd3b29d97c1f6cc3f39011da949afef934a82e6d48
Unstake done
Transaction confirm time: 2024-11-07T15:44:50.607Z
Time taken to unstake: 6533 ms
Unstake operation 3 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:45:10.615Z
hash 0x7d6e129e2d83500f0b65cf555ec4853b423bb5e9f11bbc74f46e34dae79b3e44
Unstake done
Transaction confirm time: 2024-11-07T15:45:17.122Z
Time taken to unstake: 6507 ms
Unstake operation 4 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:45:37.132Z
hash 0x9d957a5db786553ea52eb6e470585176656e8a5e5099c1cdc6b6eaf51a7ad398
Unstake done
Transaction confirm time: 2024-11-07T15:45:43.601Z
Time taken to unstake: 6469 ms
Unstake operation 5 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:46:03.612Z
hash 0x4a90d21277079ab1f669f355749f2b96c42e40274e2ec38c6ad8f1f209257479
Unstake done
Transaction confirm time: 2024-11-07T15:46:10.015Z
Time taken to unstake: 6403 ms
Unstake operation 6 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:46:30.020Z
hash 0xac630e721576b293dda2c64c9ea61f83f5fd4f3be68a58380fe6c25315c78399
Unstake done
Transaction confirm time: 2024-11-07T15:46:36.438Z
Time taken to unstake: 6418 ms
Unstake operation 7 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:46:56.446Z
hash 0xc16111a8b8eb6cc4412b820520449bf2bd73a499aa6acad608fde08f795ee3da
Unstake done
Transaction confirm time: 2024-11-07T15:47:02.974Z
Time taken to unstake: 6528 ms
Unstake operation 8 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:47:22.981Z
hash 0x31db3b1513ad9d166b1bf55f525a1dd4f3d91bd38c67bbb2a8f6b9babd371ee6
Unstake done
Transaction confirm time: 2024-11-07T15:47:30.445Z
Time taken to unstake: 7464 ms
Unstake operation 9 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:47:50.453Z
hash 0xff9b7cae7d85eddb0a4eff24d25503ecb3fbc804ab260a809195ac9d472dabb6
Unstake done
Transaction confirm time: 2024-11-07T15:47:56.956Z
Time taken to unstake: 6503 ms
Unstake operation 10 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:48:16.964Z
hash 0x065086a89c21d176b39c4a45be31a7ed0ff42f0ce5aaf38f08d208b3cf1b0979
Unstake done
Transaction confirm time: 2024-11-07T15:48:24.470Z
Time taken to unstake: 7506 ms
Unstake operation 11 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:48:44.479Z
hash 0x58b67b848e976ad4f676fdc3cf5d513476d1868b2dd4975b6bd04921450fc9f6
Unstake done
Transaction confirm time: 2024-11-07T15:48:51.227Z
Time taken to unstake: 6748 ms
Unstake operation 12 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:49:11.234Z
hash 0x1d03719ab8aa845cd17890476f65dea17608d5d5245f48b5f76347e53188d66d
Unstake done
Transaction confirm time: 2024-11-07T15:49:17.726Z
Time taken to unstake: 6492 ms
Unstake operation 13 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:49:37.733Z
hash 0x209986f491122cfa12e25cd49773cbae48b50ad2b4be5a95b36d7b3fd6b6662a
Unstake done
Transaction confirm time: 2024-11-07T15:49:44.248Z
Time taken to unstake: 6515 ms
Unstake operation 14 complete.
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:50:04.254Z
hash 0xe2217cd8a89f1f4f9383dd7086bf57b0cee6be46525e453baa4cd95500427218
Unstake done
Transaction confirm time: 2024-11-07T15:50:10.898Z
Time taken to unstake: 6644 ms
Unstake operation 15 complete.
      ✔ step04: Unstake tokens for max-unstake times (14 times) (399594ms)
Current balance of 0x9dF398707CD67f140eb19F59286b3D04CF7C383f - latest: 100061484575995148447
Current balance after unstaking:  100061484575995148447
      ✔ step05: Get delegator wallet balance after staking (548ms)
delegations:  [
  {
    delegation: {
      delegator_address: 'story1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jw9r0tc',
      validator_address: 'storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn',
      shares: '1024000000000.000000000000000000',
      rewards_shares: '512000000000.000000000000000000'
    },
    balance: { denom: 'stake', amount: '972800000000' }
  },
  {
    delegation: {
      delegator_address: 'story1huptaqvm4pckyqvs4udfrncgswdv08atzqwf6x',
      validator_address: 'storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn',
      shares: '1024000000000.000000000000000000',
      rewards_shares: '512000000000.000000000000000000'
    },
    balance: { denom: 'stake', amount: '972800000000' }
  }
]
Delegator address:  story1huptaqvm4pckyqvs4udfrncgswdv08atzqwf6x
Unbonding Delegations:  [
  {
    delegator_address: 'story1huptaqvm4pckyqvs4udfrncgswdv08atzqwf6x',
    validator_address: 'storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn',
    entries: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  }
]
unbondingDelegationCount count:  1
Assertion failed in step06: AssertionError: expected 1 to equal 15
    at Context.<anonymous> (/Users/lucas/workspace/piplabs/l1-tests/tests/long-time-test.test.ts:483:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  showDiff: true,
  actual: 1,
  expected: 15,
  operator: 'strictEqual'
}
      ✔ step06: Check the unbonding delegations, should be max 14 (759ms)
--- Start to unstake ---
Sender address: 0x9dF398707CD67f140eb19F59286b3D04CF7C383f
Unstaking...
Transaction start time: 2024-11-07T15:50:32.214Z
hash 0x908ced9ef9ed938102d95919d8673a3206f568410d9100d8fc274b6e336d634b
Unstake done
Transaction confirm time: 2024-11-07T15:50:38.442Z
Time taken to unstake: 6228 ms
      ✔ step07: Attempt 15th unstake, expect failure (26235ms)
Current balance of 0x9dF398707CD67f140eb19F59286b3D04CF7C383f - latest: 100060800975994849372
Current balance after 15th unstaking:  100060800975994849372
      ✔ step07: Get delegator wallet balance after 15th staking (534ms)


  10 passing (8m


</p>
</details> 


Get unbonding delegations response
```json
{
    "code": 200,
    "msg": {
        "unbonding_responses": [
            {
                "delegator_address": "story1huptaqvm4pckyqvs4udfrncgswdv08atzqwf6x",
                "validator_address": "storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn",
                "entries": [
                    {
                        "creation_height": "687",
                        "completion_time": "2024-11-07T15:53:54.155192043Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "1"
                    },
                    {
                        "creation_height": "701",
                        "completion_time": "2024-11-07T15:54:21.310894059Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "2"
                    },
                    {
                        "creation_height": "714",
                        "completion_time": "2024-11-07T15:54:46.652548101Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "3"
                    },
                    {
                        "creation_height": "728",
                        "completion_time": "2024-11-07T15:55:13.870345453Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "4"
                    },
                    {
                        "creation_height": "742",
                        "completion_time": "2024-11-07T15:55:41.103052936Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "5"
                    },
                    {
                        "creation_height": "755",
                        "completion_time": "2024-11-07T15:56:06.473529403Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "6"
                    },
                    {
                        "creation_height": "769",
                        "completion_time": "2024-11-07T15:56:33.763501431Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "7"
                    },
                    {
                        "creation_height": "782",
                        "completion_time": "2024-11-07T15:56:59.087409245Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "8"
                    },
                    {
                        "creation_height": "796",
                        "completion_time": "2024-11-07T15:57:26.452376575Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "9"
                    },
                    {
                        "creation_height": "810",
                        "completion_time": "2024-11-07T15:57:53.719148663Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "10"
                    },
                    {
                        "creation_height": "824",
                        "completion_time": "2024-11-07T15:58:21.288463407Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "11"
                    },
                    {
                        "creation_height": "838",
                        "completion_time": "2024-11-07T15:58:48.572059019Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "12"
                    },
                    {
                        "creation_height": "851",
                        "completion_time": "2024-11-07T15:59:13.868307665Z",
                        "initial_balance": "1024000000000",
                        "balance": "1024000000000",
                        "unbonding_id": "13"
                    },
                    {
                        "creation_height": "865",
                        "completion_time": "2024-11-07T15:59:41.330274763Z",
                        "initial_balance": "1024000000000",
                        "balance": "972800000000",
                        "unbonding_id": "14"
                    }
                ]
            }
        ],
        "pagination": {
            "total": "1"
        }
    },
    "error": ""
}
```
Get delegations for validator response

```json
{
    "code": 200,
    "msg": {
        "delegation_responses": [
            {
                "delegation": {
                    "delegator_address": "story1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jw9r0tc",
                    "validator_address": "storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn",
                    "shares": "1024000000000.000000000000000000",
                    "rewards_shares": "512000000000.000000000000000000"
                },
                "balance": {
                    "denom": "stake",
                    "amount": "972800000000"
                }
            },
            {
                "delegation": {
                    "delegator_address": "story1huptaqvm4pckyqvs4udfrncgswdv08atzqwf6x",
                    "validator_address": "storyvaloper1sv5p5rf8800nvqa90a6ezmqt8nyrdm0jq2hwqn",
                    "shares": "1024000000000.000000000000000000",
                    "rewards_shares": "512000000000.000000000000000000"
                },
                "balance": {
                    "denom": "stake",
                    "amount": "972800000000"
                }
            }
        ],
        "pagination": {
            "total": "2"
        }
    },
    "error": ""
}
```
