### ISSUE TITLE
Update validator commissionRate not applied

### ISSUE THREAD

**Issue by lucas2brh** [piplabs/story#320]
## Description and context

The genesis validator commission rate didn't update to the new rate after 1-day delay.

test case [update commission rate after 24 hours](https://www.notion.so/storyprotocol/Update-commission-rate-after-24-hours-124051299a5480108e91cbd91e5f4ad6?pvs=4).

tx:

https://devnet.storyscan.xyz/tx/0x4577874812aee8798c564d8f4bcb3344738e0c6c1db83b0458665b90aa1fcd63?tab=index

The latest rate:
```json
            {
                "operator_address": "storyvaloper1nh7zdfmxyyrwamz7s7eqewmfpn7wwws9gyue2t",
                "commission": {
                    "commission_rates": {
                        "rate": "0.000000000000000000",
                        "max_rate": "0.000000000000000000",
                        "max_change_rate": "0.000000000000000000"
                    },
                    "update_time": "2024-04-16T11:04:40.60280319Z"
                }
            },
```

## Steps to reproduce

1. call the fn to set new rate `cost rate = 1100`.
2. waiting for the delay

**Comment by lucas2brh** [comment]
I did a test again but didn't notice the correct behavior of the update validator commission.

I used the script: src/[commissionRate](https://github.com/storyprotocol/l1-tests/blob/dcc17feee9f31f9e6d67f72f4bc521688f82e3c1/src/commissionRate.ts) to send the request.

```sh
node Pubkey:  A9mdRUGE+sv2oD6jfrNvalDGmELqOtQgOKjVU3vRWyWU
commissionRate: 987
Sender address: 0xcd29b70ff04C0aa386F7b3453dF0E5eD3d4F67bb
Transaction sent: 0xf655d3fdb13a93113414331665a05ab941dd462286abbf128fb0c96ad17b35bf
Transaction confirmed: 0xf655d3fdb13a93113414331665a05ab941dd462286abbf128fb0c96ad17b35bf
```

<details><summary>0xf655d3fdb13a93113414331665a05ab941dd462286abbf128fb0c96ad17b35bf Raw trace</summary>
<p>
{
    "calls": [
        {
            "calls": [
                {
                    "from": "0xcccccc0000000000000000000000000000000001",
                    "gas": "0x8fc",
                    "gasUsed": "0x0",
                    "input": "0x",
                    "to": "0x0000000000000000000000000000000000000000",
                    "type": "CALL",
                    "value": "0xde0b6b3a7640000"
                }
            ],
            "from": "0xcccccc0000000000000000000000000000000001",
            "gas": "0x451e",
            "gasUsed": "0x449a",
            "input": "0xc582db44000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000003db000000000000000000000000000000000000000000000000000000000000004104d99d454184facbf6a03ea37eb36f6a50c69842ea3ad42038a8d5537bd15b25941a7b1cc4bf9785364b7610f33584528d74adbb1f132f0942cb176299234a11e500000000000000000000000000000000000000000000000000000000000000",
            "to": "0x333333fffffffffffffffffffffffffffffffffe",
            "type": "DELEGATECALL",
            "value": "0xde0b6b3a7640000"
        }
    ],
    "from": "0xcd29b70ff04c0aa386f7b3453df0e5ed3d4f67bb",
    "gas": "0xb18f",
    "gasUsed": "0xb013",
    "input": "0xc582db44000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000003db000000000000000000000000000000000000000000000000000000000000004104d99d454184facbf6a03ea37eb36f6a50c69842ea3ad42038a8d5537bd15b25941a7b1cc4bf9785364b7610f33584528d74adbb1f132f0942cb176299234a11e500000000000000000000000000000000000000000000000000000000000000",
    "to": "0xcccccc0000000000000000000000000000000001",
    "type": "CALL",
    "value": "0xde0b6b3a7640000"
}


</p>
</details> 

The info of validator 4 before the due date:
```json
{
    "code": 200,
    "msg": {
        "validator": {
            "operator_address": "storyvaloper1w69rjypm25h84etxxhw5ax64jg42l3gyhr0j42",
            "consensus_pubkey": {
                "type": "tendermint/PubKeySecp256k1",
                "value": "A9mdRUGE+sv2oD6jfrNvalDGmELqOtQgOKjVU3vRWyWU"
            },
            "status": 3,
            "tokens": "9599224650950000",
            "delegator_shares": "10104447001000000.000000000000000000",
            "description": {
                "moniker": "0x768A39103B552E7AE56635DD4E9B55922AAFC504"
            },
            "unbonding_height": "6799",
            "unbonding_time": "2024-11-01T15:05:48.33920484Z",
            "commission": {
                "commission_rates": {
                    "rate": "0.070000000000000000",
                    "max_rate": "0.100000000000000000",
                    "max_change_rate": "0.010000000000000000"
                },
                "update_time": "2024-04-16T11:04:40.60280319Z"
            },
            "min_self_delegation": "1024000000000",
            "unbonding_ids": [
                "285"
            ],
            "rewards_tokens": "4799612325475000.000000000000000000",
            "delegator_rewards_shares": "5052223500500000.000000000000000000"
        }
    },
    "error": ""
}
```

Noticed the same return on the due date.

**Comment by lucas2brh** [comment]
Tested on validator 01  with new rate `650`,  noticed that the Rate was applied immediately.
```sh
node Pubkey:  AqBVHHkyOfiie29Wrez6hMvC644kbZfPgXA1jFEs7Uwq
--- Start to update validator commission
commissionRate: 650
Sender address: 0xC5c0BEEAC8B37eD52F6A675eE2154D926a88E3ec
Transaction sent: 0x32bfadf462294857632c3b48d6dbf7aebb7c8cb88b1fc5e8ee7b226c6cfbbd2a
Transaction confirmed: 0x32bfadf462294857632c3b48d6dbf7aebb7c8cb88b1fc5e8ee7b226c6cfbbd2a
```
```json
            "commission": {
                "commission_rates": {
                    "rate": "0.065000000000000000",
                    "max_rate": "0.100000000000000000",
                    "max_change_rate": "0.010000000000000000"
                },
                "update_time": "2024-11-04T09:46:26.484051941Z"
            },
```

Commission before the update:
```json
                "commission": {
                    "commission_rates": {
                        "rate": "0.070000000000000000",
                        "max_rate": "0.100000000000000000",
                        "max_change_rate": "0.010000000000000000"
                    },
                    "update_time": "2024-04-16T11:04:40.60280319Z"
                },
```

Sent the tx to update again with the rate `600`.
```sh
commissionRate: 600
Sender address: 0xC5c0BEEAC8B37eD52F6A675eE2154D926a88E3ec
Transaction sent: 0x67f6ead508a76e53579932c95a06cc06d725fd010a812e0d7b655abf82020c4d
Transaction confirmed: 0x67f6ead508a76e53579932c95a06cc06d725fd010a812e0d7b655abf82020c4d
```
Noticed that the Rate remains the same.

**Comment by ezreal1997** [comment]
How long is the interval between the two txns? You can only updated commission once per 24h to the same validator.

**Comment by lucas2brh** [comment]
> How long is the interval between the two txns? You can only updated commission once per 24h to the same validator.
Several mins. 
To clarify,  the first update will be applied immediately after the genesis is our expected behavior?  If so, then we can close the issue later.

**Comment by 0xHansLee** [comment]
@lucas2brh @ezreal1997 
That's true. For genesis validator, the update time is set as `genesis_time`. That's why you can update commission rate immediately. When I tested, I created a new validator and tried to update commission rate. In case of newly created validator, the update_time is set by current time, so it requires 1 day for updating commission rate newly.
