### ISSUE TITLE
Bug Report: Validator Creation Transaction Success but Validator Not Displayed on Explorer

### ISSUE THREAD

**Issue by Coha05** [piplabs/story#347]
## Description and Context
The user attempted to create a validator using the correct method, and the transaction succeeded, but the validator did not appear on the explorer. The user retried the process three times with no success. Eventually, they moved tokens to a new wallet, used the same command to create a validator, and this time it worked as expected.

## Steps to Reproduce
1. User used the `create validator` command.
2. Transactions succeeded without any visible errors.
3. Validator did not appear on the Odyssey Testnet explorer.
4. User moved tokens to a new wallet.
5. Used the same `create validator` command with the new wallet.
6. Validator creation was successful, and the validator appeared on the explorer.

## Experienced Behavior
The validator did not appear on the explorer after repeated successful transactions from the original wallet.

## Expected Behavior
The validator should appear on the explorer after a successful `create validator` transaction.

## Solution Recommendation
The root cause of the issue is unclear. However, it appears to be related to the original wallet, given that the same command succeeded with a new wallet. Recommend investigating the following potential issues:
- Check if there are any restrictions or limitations related to specific wallet addresses.
- Verify if there are caching or synchronization issues on the explorer that may prevent validators from appearing.
- Examine if there are any silent errors in the original wallet setup affecting the validator creation. 

For reference, here are the transactions from the original and new wallets:

**Original wallet transactions:**
- [Transaction 1](https://odyssey-testnet-explorer.storyscan.xyz/tx/0x30ca40e93c9356aa6fbf45a4a555d6be4ca4ae0cfbe4d9b6210b6c4131f40de7)
- [Transaction 2](https://odyssey-testnet-explorer.storyscan.xyz/tx/0xa5033bcdcf7635468fcde65cedca54b8c6831ad5790f863eda4827a70204071f)
- [Transaction 3](https://odyssey-testnet-explorer.storyscan.xyz/tx/0x56452a67639dc0feed415b4d68221d472b6900c0f064ba823a69cdcadb1e47d9)

**Successful transaction with new wallet:**
- [New wallet transaction](https://odyssey-testnet-explorer.storyscan.xyz/tx/0x8d86cf21eae57852d1faf21c3bf4a9c122f3a4752bb1fab9f8a577019a8d8f50)

**Comment by ezreal1997** [comment]
@Coha05 thx for the feedback, we will look into it

**Comment by LeoHChen** [comment]
how to add proper test to make sure there is no regression on this issue?
