### ISSUE TITLE
stakeCLI - create validator with --unlocked returns error

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#350]
## Description and context

Run stake CLI command of create validator with --unlocked, it returns error.

## Steps to reproduce

Execute CLI command
```
story validator create --moniker create-validator-0x363c53fA13445D0Ee5685CAADc7a6E4Ff79DE28A --unlocked false --stake 5000000000000000000000 --private-key *** --rpc  http://52.0.184.238:8545
```

## Experienced behavior

It returns error:
```
ERRO !! Fatal error occurred, app died️ unexpectedly !! err="unknown command \"false\" for \"story validator create\""
```
If execute the command without `--unlocked`, it can be successful.

## Expected behavior

Should create validator successfully.

**Comment by 0xHansLee** [comment]
For boolean flag, you can try with `--unlocked=false`. It would be better to add this to doc as well. cc. @edisonz0718

**Comment by jia57b** [comment]
Tested with `--unlocked=false` in v0.13.0 story version, it doesn't return the error.
