### ISSUE TITLE
wrong flag --unstake in the validator doc for Unstake and Unstake-on-behalf

### ISSUE THREAD

**Issue by card3** [piplabs/story#361]
## Description and context

the flag prarameter "--unstake" from the doc https://docs.story.foundation/docs/odyssey-validator-operations is wrong.

## Steps to reproduce

1. ./story validator unstake --validator-pubkey ${VALIDATOR_PUB_KEY_IN_HEX} --unstake ${AMOUNT_TO_UNSTAKE_IN_WEI}
2.
3.

## Experienced behavior

Fatal error occurred, app died️ unexpectedly !! err="unknown flag: --unstake"

## Expected behavior

command run as expected.

## Solution recommendation

correct the documentation for both Unstake and Unstake-on-behalf.

**Comment by 0xHansLee** [comment]
Will be resolved in #368
