### ISSUE TITLE
require that pubkeys are on the secp256k1 curve

### ISSUE THREAD

**Issue by edisonz0718** [piplabs/story#375]
## Description and context
We currently don't check if a pubkey is on secp256k1. Only check if it's a valid length

## Suggested solution
Add the check to the contract

## Definition of done
Implement and test the change

**Comment by jdubpark** [comment]
Reference example [Secp256k1.sol](https://github.com/omni-network/omni/blob/main/contracts/core/src/libraries/Secp256k1.sol)
