### ISSUE TITLE
Update isNextProposer algorithm

### ISSUE THREAD

**Issue by edisonz0718** [piplabs/story#388]
## Description and context
Currently the isNextProposer algorithm: round-robin is different from the actual algorithm used by cometbft. We should use the same algo to pick next proposer

## Solution recommendation
Query cometbft to get the correct next proposer. Reference from omni: https://github.com/omni-network/omni/pull/2526/files#diff-5b776d2b7b8e2c9264856050ff385fcf806c6d2d7eca60cc4a54c96065620e24

**Comment by jdubpark** [comment]
Two notes:
1. This is backward-compatible as it's an optimistic check for a local node to determine if it should optimistically build the next block (as it predicts it will be the next proposer). Differences in this function do not impact consensus, but a correct algo to determine the next proposer will improve performance.
2. Optimistic building will only work correctly (as in the blocks built optimistically will be used as the next block) if this `isNextProposer` works correctly.
3. We need to determine how optimistic building impacts block building as nodes (next proposers) will stop collecting transactions earlier than what the network does right now (with optimistic building turned off).
