### ISSUE TITLE
Pre-deployed CREATE3 deployer seems doesn't work on Odyssey

### ISSUE THREAD

**Issue by kingster-will** [piplabs/story#404]
The pre-deployed create3 `0x9fBB3DF7C40Da2e5A0dE984fFE2CCB7C47cd0ABf` seems doesn’t work on Odyssey. 57 block reported the protocol deploy failed on Odyssey with error below, and I reproduced the same error above when deploy the protocol. Please kindly take a look

```
0x9fBB3DF7C40Da2e5A0dE984fFE2CCB7C47cd0ABf::getDeployed(0xad229ca44fc156b1f47f7ed5b90802bf978b9ab121c0d1afa84276cbf906dc4c) [staticcall]
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert
```

**Comment by Ramarti** [comment]
CREATE3 has 2 parameters, salt and deployer. This call has only 1
https://github.com/piplabs/story/blob/b66ad4aa04eea82c10d0607c651c10bf73587eaf/contracts/src/deploy/Create3.sol#L35
We are using Omni's version, which is the original one, for max compatibility.
https://github.com/ZeframLou/create3-factory/blob/main/src/CREATE3Factory.sol

The address is calculated combining salt and deployer address. This makes it so we have less collisions and people can't "squat" particular salt values.

**Comment by Ramarti** [comment]
Closed by https://github.com/piplabs/story/pull/437
