### ISSUE TITLE
StakeCLI - Creating a validator failed

### ISSUE THREAD

**Issue by jia57b** [piplabs/story#429]
## Description and context

Execute story (release/0.15) command of create validator failed, it might be caused by contract change https://github.com/piplabs/story/commit/b7ba2d93a821d629fae4b6ad31a210ac6f1d2abf, cli need to be updated

## Steps to reproduce

Execute story command:
`story validator create --moniker test-0x919d5572636dEeC1390F64e7F97a33c9AF8670d2 --unlocked=true --stake 1024000000000000000000 --private-key*** --rpc  http://r1-d.odyssey-devnet.storyrpc.io:8545 --chain-id 1315 --explorer https://devnet.storyscan.xyz`

## Experienced behavior

The command returns error:
`24-12-13 02:35:21.492 ERRO !! Fatal error occurred, app died️ unexpectedly !! err="failed to estimate gas: execution reverted" stacktrace="[errors.go:39 transaction.go:162 transaction.go:92 transaction.go:41 validator.go:464 validator.go:171 validator.go:411 command.go:985 command.go:1117 command.go:1041 command.go:1034 cmd.go:34 main.go:10 proc.go:271 asm_amd64.s:1695]"`

## Expected behavior

the command should be successful.

**Comment by limengformal** [comment]
It might be due to createValidatorOnBehalf being removed per this [commit](https://github.com/piplabs/story/commit/b7ba2d93a821d629fae4b6ad31a210ac6f1d2abf).

**Comment by jia57b** [comment]
Fixed in the [PR](https://github.com/piplabs/story/pull/431)
