### ISSUE TITLE
unjail subcommand doesn't exist yet on story client

### ISSUE THREAD

**Issue by McDaan** [piplabs/story#80]
## Description and context
Unjail subcommand doesn't exist yet.

## Suggested solution
Add unjail subcommand to let operators unjail after a downtime behaviour.

**Comment by edisonz0718** [comment]
Yes. The unjail function currently is not functional in Iliad testnet. We are aware of this issue and will address in the upcoming releases.  Once the issue is fixed, we will add it to the cli.
