### ISSUE TITLE
Error in GetWithdrawalQueue and make bufgen Command Failure

### ISSUE THREAD

**Issue by ByungHeonLEE** [piplabs/story#84]
## Description and context
- The `GetWithdrawalQueue` function is not functioning correctly due to un-marshalling fail
- Additionally, the `make bufgen` command is not working as expected

## Steps to reproduce
1. Copy & Create [grpc_query_test.go](https://gist.github.com/zsystm/c4f76bb003151e44a5b77b903b12445e) to `client/x/evmstaking/keeper` 
2. Run the test code
3. Run the`make bufgen` to generate `pb.go`

## Experienced behavior
- The `GetWithdrawalQueue`function fails with a Protobuf error.
> `rpc error: code = Internal desc = proto: Withdrawal: illegal tag 0 (wire type 0)`
- The `make bufgen`command does not run successfully

## Solution recommendation
- Debug the value(0x03), stored on`WithdrawalQueueKey`prefix and make `withdrawals`as proper protobuf 
- Update the `buf_generate.sh`file

**Comment by edisonz0718** [comment]
What is the error when you run `make bufgen` ? It runs fine for me.

**Comment by zsystm** [comment]
@ByungHeonLEE 
`make bufgen` would work if you install the following binaries and run again.
```
go install github.com/cosmos/cosmos-proto/cmd/protoc-gen-go-pulsar
go install github.com/cosmos/gogoproto/protoc-gen-cosmos
go install github.com/cosmos/gogoproto/protoc-gen-go-cosmos-orm
go install cosmossdk.io/orm/cmd/protoc-gen-go-cosmos-orm
go install google.golang.org/protobuf/cmd/protoc-gen-go
```

@edisonz0718 
It would be great to add an auto-installation feature that checks for the required binaries needed to compile proto locally and installs them if they do not exist.

**Comment by edisonz0718** [comment]
Yes, I think we have a separate `make install-go-tools` to install the dependency. We can check if the binaries exist and run this first before `make bufgen`
