### ISSUE TITLE
More command line such as send $IP, withdraw reward.

### ISSUE THREAD

**Issue by Obiwank107** [piplabs/story#93]
Please add command line for send $IP and withdraw $IP staking reward.

**Comment by zsystm** [comment]
@Obiwank107 

- You can send $IP via eth transaction to Execution Client(= Geth)
- Accumulated IP staking rewards are automatically withdrawn by [evmstaking.EndBlocker](https://github.com/piplabs/story/blob/20f3f6bc9b6d6653279927d6ed8259f38dccb7af/client/x/evmstaking/keeper/abci.go#L133-L139) if the amount is bigger than [MinPartialWithdrawalAmount](https://github.com/piplabs/story/blob/a79b2417fc928d1c4823745d03ff2315a74dd67b/client/x/evmstaking/keeper/withdraw.go#L57)

**Background knowledge**
- User can only interact with Execution Layer (= Geth)
- User cannot directly send txs to consensus client. 
- To trigger allowed state transition (e.g. `CreateValidator`, `Stake`, `Unstake`, etc...), you need to send eth tx to [protocol contracts](https://github.com/piplabs/story/tree/main/contracts/src/protocol) deployed on Execution Layer (= Geth)

<img width="1670" alt="image" src="https://github.com/user-attachments/assets/e9d801e7-af29-4e1c-a646-6701a11a17fb">
